"""init

Revision ID: ba8d23494368
Revises: 
Create Date: 2025-07-20 12:45:18.238122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8d23494368'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор кошелька'),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False, comment='Текущий баланс в минимальных единицах (копейки, центы)'),
    sa.CheckConstraint('balance >= 0', name='non_negative_balance'),
    sa.PrimaryKeyConstraint('id'),
    comment='Кошельки пользователей'
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
